# Generated by Django 3.2.5 on 2022-07-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_order_orderdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='driver',
            new_name='order',
        ),
    ]
